name: Linting
on:
  pull_request:

jobs:
  prose:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Vale
      uses: errata-ai/vale-action@reviewdog
      with:
        # Please keep version in sync with the version in .gitpod.Dockerfile for a consistent experience
        version: 2.29.2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  prose_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip3 install -r docs/requirements.txt

      - name: Vale install
        working-directory: docs
        run: mkdir -p vale && cd vale && wget https://github.com/errata-ai/vale/releases/download/v2.29.2/vale_2.29.2_Linux_64-bit.tar.gz && tar -xf vale_2.29.2_Linux_64-bit.tar.gz && mv ./vale /usr/local/bin/vale && ../ && rm -rf vale

      - name: Vale check
        working-directory: docs
        run: vale ./

  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - uses: actions/setup-python@v4
      with:
        python-version: '3.x'
        cache: 'pip'

    - name: Install Python dependencies
      run: pip3 install -r docs/requirements.txt

    - name: Build docs
      working-directory: docs
      run: make html

    - name: Check links
      working-directory: docs
      run: make checklinks
